services:
  proxy:
    build:
      context: ..
      dockerfile: ./.local-build/proxy/Dockerfile
    ports:
      - "${WEB_HOST_PORT:-8080}:8080"
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    restart: on-failure
  frontend:
    build:
      context: ..
      dockerfile: ./.local-build/frontend/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        PNPM_VERSION: ${PNPM_VERSION}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-/api}
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
    restart: on-failure
  backend:
    build:
      context: ..
      dockerfile: ./.local-build/backend/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        PNPM_VERSION: ${PNPM_VERSION}
    environment:
      PORT: 3000
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      NODE_ENV: ${NODE_ENV}
    restart: on-failure
  prisma:
    build:
      context: ..
      dockerfile: ./.local-build/prisma/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        PNPM_VERSION: ${PNPM_VERSION}
    environment:
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      ENABLE_DB_SEED: ${ENABLE_DB_SEED:-false}
      ENABLE_PRISMA_STUDIO: ${ENABLE_PRISMA_STUDIO:-false}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${PRISMA_STUDIO_HOST_PORT:-5555}:5555"
    depends_on:
      db:
        condition: service_healthy
    restart: no
  db:
    image: postgres:16.11
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: ${TZ}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s
    restart: on-failure

volumes:
  db_data: {}
